{
"name":"http://sparql.lod4wfs.de/dbpedia_10k",
"title":"10k entries in DBpedia",
"abstract":"10k random places in DBpedia. Retrieved via SPARQL.",
"keywords":"dbpedia, places",
"geometryVariable":"?wkt",
"endpoint":"http://dbpedia.org/sparql",
"query":"PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX  geo:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX  dbo:  <http://dbpedia.org/ontology/>

SELECT DISTINCT  (concat('POINT(', ?long, ' ', ?lat, ')') AS ?wkt) ?label ?population ?abstract ?lat ?long 
WHERE
  { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> dbpedia-owl:Place .
    ?s geo:lat ?lat .
    ?s geo:long ?long .
    ?s rdfs:label ?label .
    ?s dbpedia-owl:abstract ?abstract
    FILTER langMatches(lang(?abstract), 'EN')
    ?s dbpedia-owl:populationTotal ?population
    FILTER langMatches(lang(?label), 'EN')
  } 
limit 10
"
}