{
"name":"http://sparql.lod4wfs.de/dbpedia_10k",
"title":"10k entries in DBpedia",
"abstract":"10k random places in DBpedia. Retrieved via SPARQL.",
"keywords":"dbpedia, places",
"geometryVariable":"?wkt",
"endpoint":"http://dbpedia.org/sparql",
"crs":"EPSG:4326",
"enabled":"true",
"toc": [
	{"wkt": "http://www.w3.org/2001/XMLSchema#string"},
	{"label": "http://www.w3.org/2001/XMLSchema#string"},
	{"my_population": "http://www.w3.org/2001/XMLSchema#nonNegativeInteger"},
	{"abstract": "http://www.w3.org/2001/XMLSchema#string"},
	{"lat": "http://www.w3.org/2001/XMLSchema#float"},
	{"long": "http://www.w3.org/2001/XMLSchema#float"}
	],
"query":"PREFIX  geo:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX  dbo:  <http://dbpedia.org/ontology/>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT DISTINCT  (concat('POINT(', ?long, ' ', ?lat, ')') AS ?wkt) ?label ?my_population ?abstract ?lat ?long
WHERE
  { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> dbo:Place .
    ?s geo:lat ?lat .
    ?s geo:long ?long .
    ?s rdfs:label ?label .
    ?s dbo:abstract ?abstract
    FILTER langMatches(lang(?abstract), 'EN')
    ?s dbo:populationTotal ?my_population
    FILTER langMatches(lang(?label), 'EN')
  }
"
}