{
"name":"http://sparql.lod4wfs.de/getty_places",
"title":"Getty Thesaurus Places",
"abstract":"no abstract",
"keywords":"no keywords",
"geometryVariable":"?wkt",
"endpoint":"http://vocab.getty.edu/sparql",
"crs":"EPSG:4326",
"enabled":"true",
"toc": [
	{"place": "http://www.w3.org/2001/XMLSchema#string"},
	{"name": "http://www.w3.org/2001/XMLSchema#string"},
	{"parentString": "http://www.w3.org/2001/XMLSchema#string"},
	{"wkt": "http://www.w3.org/2001/XMLSchema#string"}
	],
"query":"PREFIX  schema: <http://schema.org/>
PREFIX  wgs:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX  tgn:  <http://vocab.getty.edu/tgn/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  xl:   <http://www.w3.org/2008/05/skos-xl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  gvp:  <http://vocab.getty.edu/ontology#>
PREFIX  ontogeo: <http://www.ontotext.com/owlim/geo#>

SELECT  ?place ?name ?parentString (concat('POINT(', xsd:string(?long), ' ', xsd:string(?lat), ')') AS ?wkt)
WHERE
  { ?feature skos:inScheme tgn: .
    ?feature gvp:parentString ?parentString .
    ?feature foaf:focus ?place .
    ?feature gvp:prefLabelGVP _:b0 .
    _:b0 xl:literalForm ?name .
    ?place wgs:lat ?lat .
    ?place wgs:long ?long .
    ?place <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:Place
  }
"
}