{
"name":"http://sparql.lod4wfs.de/historic_things",
"title":"Historic Things at GeoNames",
"abstract":"no abstract",
"keywords":"no keywords",
"geometryVariable":"?wkt",
"endpoint":"http://linkedgeodata.org/sparql",
"query":"PREFIX  wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT  ?historicthing ?label ?wkt
WHERE
  { ?historicthing wgs84_pos:lat ?lat .
    ?historicthing wgs84_pos:long ?long .
    ?historicthing <http://geovocab.org/geometry#geometry> ?geometry .
    ?geometry <http://www.opengis.net/ont/geosparql#asWKT> ?wkt .
    ?historicthing <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://linkedgeodata.org/ontology/HistoricThing>
    OPTIONAL
      { ?historicthing <http://www.w3.org/2000/01/rdf-schema#label> ?label }
    FILTER langMatches(lang(?label), 'EN')
  }

"
}