{
"name":"http://sparql.lod4wfs.de/historic_maps",
"title":"ULB Historic Maps Repository",
"abstract":"no abstract",
"keywords":"no keywords",
"geometryVariable":"?wkt",
"endpoint":"http://data.uni-muenster.de:8080/openrdf-sesame/repositories/oldmaps",
"query":" PREFIX maps: <http://www.geographicknowledge.de/vocab/maps#>
PREFIX geo: <http://www.opengis.net/ont/geosparql/1.0#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX luc: <http://www.ontotext.com/owlim/lucene#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
SELECT
DISTINCT
?map
?title
?scale
?wkt
?picture
?year
?description
WHERE {
?map a maps:Map.
?map maps:digitalImageVersion ?picture.
?map maps:title ?title.
?map maps:hasScale ?scale.
?map maps:mapsArea ?area.
?map maps:mapsTime ?time.
?time xsd:gYear ?year.
?area geo:asWKT ?wkt.
OPTIONAL
{
?map dct:description ?description.
} .
}
ORDER BY
?year
"
}