{
"name":"http://sparql.lod4wfs.de/piracy",
"title":"Piracy Data",
"abstract":"no abstract",
"keywords":"no keywords",
"geometryVariable":"?wkt",
"endpoint":"http://semanticweb.cs.vu.nl/lop/sparql/",
"query":"PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
   PREFIX poseidon: <http://semanticweb.cs.vu.nl/poseidon/ns/instances/>
   PREFIX eez: <http://semanticweb.cs.vu.nl/poseidon/ns/eez/>
   PREFIX wgs84: <http://www.w3.org/2003/01/geo/wgs84_pos#>
   PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
   
   SELECT ?place (CONCAT('POINT(', str(?long), ' ', str(?lat), ')') AS ?wkt) 
   WHERE {
     ?event sem:eventType ?event_type .
     ?event sem:hasPlace ?place .
     ?place wgs84:lat ?lat .
     ?place wgs84:long ?long .
   }
"
}