
{
 "title":"a title 2",
 "abstract":"an abstract 1",
 "name":"http://ifgi.uni-muenster.de/dummy",
 "keywords":"some key words 1",
 "query":"SELECT ?subject ?predicate ?object ?commander ?name ?birthdate
		  WHERE {
			    ?subject ?predicate ?object .
			    <http://data.uni-muenster.de/historicmap/minardsmap> <http://purl.org/dc/terms/references> ?object .   
			 {
			  SERVICE <http://dbpedia.org/sparql/> {
			         ?object a <http://dbpedia.org/ontology/MilitaryConflict> .
			         ?object <http://dbpedia.org/ontology/commander> ?commander .   
			        ?commander <http://dbpedia.org/property/name> ?name .
			        ?commander <http://dbpedia.org/property/birthDate> ?birthDate   
			  }

			}
			}"
}
